@host = http://localhost:4000/v1

POST {{host}}/movies
Content-Type: application/json
Authorization: Bearer LNY3EW4LWAJS4ZWE3KFDXUVA5A

{
    "title": "Deadpool",
    "year": 2016,
    "runtime": "108 mins",
    "genres": [
        "Action",
        "Comedy"
    ]
}
